apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: redis
    image: redis:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 6379

  - name: server
    image: Irakai/microservices:server-v1
    ports:
    - containerPort: 8080
    env:
    - name: REDIS_URL
      value: redis://localhost:6379

  - name: counter
    image: Irakai/microservices:counter-v1
    ports:
    - containerPort: 8081
    env:
    - name: API_URL
      value: http://localhost:8080

  - name: poller
    image: Irakai/microservices:poller-v1
    env:
    - name: API_URL
      value: http://localhost:8080
