apiVersion: v1
kind: Service
metadata:
  name: app-tier
  labels:
    app: microservices
spec:
  ports:
  - port: 8080
  selector:
    tier: app
---
apiVersion: v1
kind: Pod
metadata:
  name: app-tier
  labels:
    app: microservices
    tier: app
spec:
  containers:
  - name: server
    image: lrakai/microservices:server-v1
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 8080
    env:
      - name: REDIS_URL
      # Environment variable for Service Discovery
      #Naming Pattern:
      # IP address: <all_caps_service_name>_SERVICE_HOST
      # Port: <all_caps_service_name>_SERVICE_PORT
      # Named Port: <all_caps_service_name>_SERVICE_PORT_<all_caps_port_name>_PORT
        value: redis://$(DATA_TIER_SERVICE_HOST):$(DATA_TIER_SERVICE_PORT_REDIS)
      
      # In multicontainer example value was
      #value: redis://localhost:6379