apiVersion: v1
kind: Pod
metadata:
  name: pod101
  namespace: ckaprep
  labels:
    app: pod101
    type: test
spec:
  containers:
  - name: mycontainer
    image: nginx:latest
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "25m"
      limits:
        memory: "128Mi"
        cpu: "50m"
