apiVersion: v1
kind: Pod
metadata:
  name: support-tier
  labels:
    app: microservices
    tier: support
spec:
  containers:
    - name: counter
      image: lrakai/microservices:counter-v1
      imagePullPolicy: IfNotPresent
      env:
        - name: API_URL
          # DNS for service discovery
          # Naming Pattern:
          # IP address: <service_name>.<service_namespace>
          # Port: needs to be extracted from the SRV DNS Record
          value: http:app-tier.servicediscovery:8080

    - name: poller
      image: lrakai/microservices:poller-v1
      imagePullPolicy: IfNotPresent
      env:
        - name: API_URL
          value: http:app-tier:$(APP_TIER_SERVICE_PORT)