- name: Install git on local machine
  hosts: local
  become: true   # Use become to run tasks with elevated privileges (like sudo as root)
  tasks:
    - name: Ensure apt cache is up to date
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install git
      apt:
        name: git
        state: present
